config/routes.rb
Rails.application.routes.draw do

post "/Account/VIPLogin", to: "welcome#viplogin"
  get "/Home/Contact", to: "welcome#homecontact"
  get "/Chat/Favorites", to: "welcome#favorites"
  get "/Chat/Followers", to: "welcome#followers"
  get "/Chat/Conversations", to: "welcome#conversations"
  post "/Account/Register", to: "welcome#createaccount"  
  get "/Account/Register", to: "welcome#register"  
  get "/Account/VIPLogin", to: "welcome#login", as: :accountviplogin
get "Chat/search", to: "welcome#search", as: :tracechat
get "/Chat/profile/TchatchePass:id", to: "welcome#myprofileuser", as: :tchatchepass
get "Chat", to: "welcome#search"
get "/Chat/newinterlocutors", to: "welcome#mesmessages", as: :newinterlocutors
get "/Chat/conversation/TchatchePass:id", to: "welcome#tchatche", as: :tchatcheconversation
get "/Chat/map", to: "welcome#map"
get "/Chat/SettingsVIPProfile", to: "welcome#settingsvip" 
patch "/Chat/SettingsVIPProfile", to: "welcome#settingsvipme" 
post "updateuserpicture", to: "welcome#updateuserpicture"
get "/Chat/SettingsDating", to: "welcome#settingsdating" 
patch "/Chat/SettingsDating", to: "welcome#settingsdatingme" 
get "/Chat/SettingsAccount", to: "welcome#settingsaccount" 
get "/Chat/SettingsAlbums", to: "welcome#settingsalbums" 
get "/Chat/SettingsInterests", to: "welcome#settingsinterests", as: :settingsinterests 
post "loademoticons", to: "welcome#loademoticons", as: :loademoticons
post "loadphotos:id", to: "welcome#loadphotos", as: :loadphotos
patch "/Chat/SettingsAccount", to: "welcome#editsettingsaccount", as: :editsettingsaccount
post "findnewconnecte", to: "welcome#findnewconnected", as: :search_new_connected
post "findconnecte", to: "welcome#findconnecte", as: :searchconnect
post "addpublic", to: "welcome#addpublic"
post "addprivate", to: "welcome#addprivate"
post "moveotheralbum", to: "welcome#moveotheralbum"
post "profilepic", to: "welcome#profilepic"
post "deletephoto", to: "welcome#deletephoto"
root to: 'welcome#index'
post "/api/vips/TchatchePass:id", to: "welcome#ratinguser", as: :rating
post "/api/abuse/TchatchePass:id", to: "welcome#abuse", as: :abuse
post "/api/addtoblacklist/TchatchePass:id", to: "welcome#addtoblacklist", as: :addtoblacklist
post "/api/removefromblacklist/TchatchePass:id", to: "welcome#removefromblacklist", as: :removefromblacklist
post "/api/deletefromfavorites/TchatchePass:id", to: "welcome#deletefromfavorites", as: :deletefromfavorites
post "/api/selectpicturetosend/TchatchePass:id", to: "welcome#selectpicturetosend", as: :selectpicturetosend
post "/api/sendmessage/TchatchePass:id", to: "welcome#sendmessage", as: :sendmessage
post "/api/addtofavorites/TchatchePass:id", to: "welcome#addtofavorites", as: :addtofavorites
post "/api/deleteinterlocutor/TchatchePass:id", to: "welcome#deleteinterlocutor", as: :deleteinterlocutor
post "/api/smiley/TchatchePass:id", to: "welcome#sendsmiley", as: :sendsmiley
post "/api/refreshchatinterlocutor/TchatchePass:id", to: "welcome#refreshchatinterlocutor", as: :refreshchatinterlocutor
patch "/Chat/SettingsInterests", to: "welcome#settingsinterestsme"
  devise_scope :user do
post "/Chat/Logout", to: "users/sessions#destroy", as: :logout
end
devise_for :users
mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_emoticons.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-part emoticons-wrapper shown" data-bind="css: { 'shown': $parent.emoticonsAreVisible }">
                                        <div class="close" onclick="closeeverything(e);return false;" data-bind="click: $parent.hideEmoticons">
                                            <span class="icon icon-close" onclick="closeeverything();return false;"></span>
                                        </div>
                                        <div data-bind="component : { name : 'emoticon', params : { event : $parent.event } }">
    <div class="emoticon-container">
        <ul class="list-unstyled list-inline" data-bind="foreach: emoticons">
            <li>
                <span class="smiley pointer emoji1" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji2" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji3" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji4" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji5" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji6" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji7" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji8" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji9" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji10" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji11" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji12" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji13" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji14" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji15" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji16" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji17" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji18" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji19" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji20" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji21" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji22" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji23" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji24" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji25" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji26" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji27" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji28" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji29" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji30" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji31" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji32" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji33" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji34" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji35" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji36" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        
            <li>
                <span class="smiley pointer emoji37" data-bind="css: $data.getCssClass(), event: { click: $parent.selectEmoticon }"></span>
            </li>
        </ul>
    </div>
</div>
                                    </div>

app/views/application/_interlocutor.html.erb
<li class="pointer chatter <%=user == current_user ? "isMe" : ""%>" data-bind="css: { 'isMe': isMe }">
                        <a data-bind="attr: { 'href': $parent.getProfileUrl($data.id) }" class="stretch display-b" href="<%=tchatchepass_path(id: user.id)%>">
                            <div class="border-gender pull-left <%if user.iswoman?%>bg-woman<%else%>bg-man<%end%>" data-bind="css: { 'bg-man': isAMan, 'bg-woman': isAWoman }"></div>
                            <div data-bind="component : { name : 'chatterinfo', params : { event : $parents[1].event, chatter : $data, templateName: 'default-chatter-info-template', pictureTemplate: 'chatter-picture-default-template' } }">
    <div class="chatter-info-template" data-bind="template : { name : templateName }">
    <div class="chatter-infos-container fix-height <%if user.iswoman?%>woman<%else%>man<%end%>" data-bind="css:{ 'man': chatter.isAMan, 'woman': chatter.isAWoman }">
<%if user.image%>
        <div class="pull-left chatter-picture" data-bind="if: chatter.hasProfilePicture">
<%begin%>
<%if asset_path(user.image)%>
<div class="chatter-picture-template" data-bind="template : { name : pictureTemplate }">
    <div class="picture-container">
        <div class="picture stretch" data-bind="style: { 'background-image': getBackgroundStyledPictureUrl }" style="background-image: url('<%=asset_path(user.image)%>');width:50px;height:50px;"></div>
        <div class="online">
                    <span class="icon icon-online <%if user.online%>online<%else%>offline<%end%>" data-bind="css: { 'online': chatter.isConnected, 'offline': chatter.isDisconnected }"></span>
                </div>
    </div>
</div>

<%end%>
<%rescue =>e%>
<div class="avatar-container <%if user.iswoman?%>avatar-woman<%else%>avatar-man<%end%>" data-bind="css: { 'avatar-man': chatter.isAMan, 'avatar-woman': chatter.isAWoman }">
                
                <div class="online">
                    <span class="icon icon-online <%if user.online%>online<%else%>offline<%end%>" data-bind="css: { 'online': chatter.isConnected, 'offline': chatter.isDisconnected }"></span>
                </div>
            </div>
<%end%>

</div>
<%else%>
        <div class="pull-left chatter-picture" data-bind="if: !chatter.hasProfilePicture">
            <div class="avatar-container <%if user.iswoman?%>avatar-woman<%else%>avatar-man<%end%>" data-bind="css: { 'avatar-man': chatter.isAMan, 'avatar-woman': chatter.isAWoman }">
                
                <div class="online">
                    <span class="icon icon-online <%if user.online%>online<%else%>offline<%end%>" data-bind="css: { 'online': chatter.isConnected, 'offline': chatter.isDisconnected }"></span>
                </div>
            </div>
        </div>
<%end%>
        <div class="chatter-infos">
            <span class="chatter-name" data-bind="text: chatter.name"><%=user.name%></span>
            <div class="infos">
                <div class="row-infos age">
                    <span data-bind="if: chatter.isAMan">
                        <%if user.isman?%>Man,<%end%>
                    </span>
                    <span data-bind="if: chatter.isAWoman"><%if user.iswoman?%>Woman,<%end%></span>
                    <span data-bind="text: chatter.age"><%=user.sonage%></span> years old
                </div>
                <div class="row-infos">
                    <span data-bind="text: chatter.country">FRA</span>
                    <span data-bind="text: chatter.htmlSubdivision">(88)</span>
                </div>
                <div class="infos-row">
                    <span data-bind="if: chatter.vip">
                        <span class="icon icon-vip"></span>
                    </span>
                    <span class="<%=user.malesearched ? "icon-man" : nil%>" data-bind="if: chatter.isLookingForMan"></span>
                    <span class="<%=user.femalesearched ? "icon-woman" : nil%>" data-bind="if: chatter.isLookingForWoman"></span>
                    <span data-bind="if: chatter.isLookingForBoth"></span>
                    <span data-bind="if: chatter.vip &amp;&amp; chatter.isLookingForUnknown">
                        <span class="icon icon-spacer"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
                        </a>
                    </li>
                    <!-- ko if: $parent.canShowCMPCheckMessage($index()) --><!-- /ko -->
                

app/views/application/_mediastosend.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-part medias-to-send-wrapper shown" data-bind="css: { 'shown': $parent.mediasToSendAreVisible }">
                                        <div class="close" data-bind="click: $parent.hideMediasToSend">
                                            <span class="icon icon-close"></span>
                                        </div>
                                        <div data-bind="with : $parent.sender">
                                            <div data-bind="if: hasMedias">
                                        <%if current_user.privatephotos.length > 0 %>
<ul class="list-unstyled list-inline slider " data-bind="foreach: privatePhotos">
       <%=render partial: "myprivatephotostosend", collection: current_user.privatephotos, as: :photo%>                                                        

                            </ul>                                    

<%end%>
                                        </div>
                                            
                                            <div data-bind="if: hasNoMedia" class="text-center">
                                        <%if current_user.privatephotos.length == 0%>
                                    

                                                <a href="/Chat/SettingsAlbums">
                                                    Your albums are empty. Add photos to send to your contacts.
                                                </a>
                                        <%end%>
                                            </div>
                                            
                                        </div>
                                    </div>

app/views/application/_mynewmessage.html.erb
<li class="interlocutor">
                        <div class="col-xs-10 col-sm-6 col-md-8 col-lg-8 border" data-bind="click: $parent.showConversation">
                            <div class="border-gender pull-left bg<%=user.sendergender == "M" ? "-man" : "-woman"%>" data-bind="css: { 'bg<%=user.sendergender == "M" ? "-man" : "-woman"%>': isAMan, 'bg-woman': isAWoman }"></div>
                            <div class="pointer" data-bind="component : { name : 'chatterinfo', params : { event : $parent.event, chatter : $data, templateName: 'default-chatter-info-template', pictureTemplate: 'chatter-picture-default-template' } }">
    <div class="chatter-info-template" data-bind="template : { name : templateName }">
    <div class="chatter-infos-container fix-height<%=user.sendergender == "M" ? " man" : " woman"%>" data-bind="css:{ 'man': chatter.isAMan, 'woman': chatter.isAWoman }">
        <div class="pull-left chatter-picture" data-bind="if: chatter.hasProfilePicture"></div>
        <div class="pull-left chatter-picture" data-bind="if: !chatter.hasProfilePicture">
            <div class="avatar-container avatar<%=user.sendergender == "M" ? "-man" : "-woman"%>" data-bind="css: { 'avatar<%=user.sendergender == "M" ? "-man" : "-woman"%>': chatter.isAMan, 'avatar-woman': chatter.isAWoman }">
                
                <div class="online">
                    <span class="icon icon-online online" data-bind="css: { 'online': chatter.isConnected, 'offline': chatter.isDisconnected }"></span>
                </div>
            </div>
        </div>
        <div class="chatter-infos">
            <span class="chatter-name" data-bind="text: chatter.name"><%=user.sendername%></span>
            <div class="infos">
                <div class="row-infos age">
                    <span data-bind="if: chatter.isAMan">
                        <%=user.sendergender == "M" ? "Man," : ""%>
                    </span>
                    <span data-bind="if: chatter.isAWoman">
                    <%=user.sendergender == "M" ? "Woman," : ""%>
                    </span>
                    <span data-bind="text: chatter.age"><%=user.senderage%></span> years old
                </div>
                <div class="row-infos">
                    <span data-bind="text: chatter.country">FRA</span>
                    <span data-bind="text: chatter.htmlSubdivision">(62)</span>
                </div>
                <div class="infos-row">
                    <span data-bind="if: chatter.vip">
                        <%if user.persisted?%>
                        <span class="icon icon-vip"></span>
                        <%end%>
    </span>
                    <span data-bind="if: chatter.isLookingForMan">
                        <%if user.sendermalesearched%>
                        <span class="icon icon-man text-man" title="Looking for a man"></span>
                        <%end%>


</span>
                    <span data-bind="if: chatter.isLookingForWoman">
                        <%if user.senderfemalesearched%>
                        <span class="icon icon-woman text-woman" title="Looking for a woman"></span>
                        <%end%>
                    </span>
                    <span data-bind="if: chatter.isLookingForBoth"></span>
                    <span data-bind="if: chatter.vip &amp;&amp; chatter.isLookingForUnknown"></span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
                        </div>
                        <div class="col-xs-1 col-sm-3 col-md-2 col-lg-2 border actions text-vip">
                            <div class="pointer text-center awaiting-reply">
                                <span class="icon icon-new-message fs-2x" onclick="window.location='<%=tchatcheconversation_path(id: user.sender_id)%>';" data-bind="click: $parent.showConversation"></span>
                                <span class="text" onclick="window.location='<%=tchatcheconversation_path(id: user.sender_id)%>';" data-bind="click: $parent.showConversation">Reply</span>
                            </div>
                        </div>
                        <div class="col-xs-1 col-sm-3 col-md-2 col-lg-2 actions text-vip">
                            <div class="pointer text-center">
                                <span class="icon icon-delete fs-2x" data-bind="click: $parent.deleteInterlocutor"></span>
                                <span class="text" data-bind="click: $parent.deleteInterlocutor">Delete</span>
                            </div>
                        </div>
                    </li>

app/views/application/_myprivatephotostosend.html.erb
 <li class="slide profile-media">
                                    <div class="stretch imageprofile item" data-id="15" data-id="<%=photo.id%>" style="background-image: url('/assets/<%=photo.url%>');"  data-bind="style: { 'background-image': $parent.getBackgroundStyledPictureUrl(url) }, click: $parent.selectPrivatePicture"></div>
                                    
                                </li>

app/views/application/_newmessage.html.erb
<li class="interlocutor">
                        <div class="col-xs-10 col-sm-6 col-md-8 col-lg-8 border" data-bind="click: $parent.showConversation">
                            <div class="border-gender pull-left bg-man" data-bind="css: { 'bg-man': isAMan, 'bg-woman': isAWoman }"></div>
                            <div class="pointer" data-bind="component : { name : 'chatterinfo', params : { event : $parent.event, chatter : $data, templateName: 'default-chatter-info-template', pictureTemplate: 'chatter-picture-default-template' } }">
    <div class="chatter-info-template" data-bind="template : { name : templateName }">
    <div class="chatter-infos-container fix-height man" data-bind="css:{ 'man': chatter.isAMan, 'woman': chatter.isAWoman }">
        <div class="pull-left chatter-picture" data-bind="if: chatter.hasProfilePicture"></div>
        <div class="pull-left chatter-picture" data-bind="if: !chatter.hasProfilePicture">
            <div class="avatar-container avatar-man" data-bind="css: { 'avatar-man': chatter.isAMan, 'avatar-woman': chatter.isAWoman }">
                
                <div class="online">
                    <span class="icon icon-online online" data-bind="css: { 'online': chatter.isConnected, 'offline': chatter.isDisconnected }"></span>
                </div>
            </div>
        </div>
        <div class="chatter-infos">
            <span class="chatter-name" data-bind="text: chatter.name">keviinshomm</span>
            <div class="infos">
                <div class="row-infos age">
                    <span data-bind="if: chatter.isAMan">
                        Man,
                    </span>
                    <span data-bind="if: chatter.isAWoman"></span>
                    <span data-bind="text: chatter.age">30</span> years old
                </div>
                <div class="row-infos">
                    <span data-bind="text: chatter.country">FRA</span>
                    <span data-bind="text: chatter.htmlSubdivision">(62)</span>
                </div>
                <div class="infos-row">
                    <span data-bind="if: chatter.vip">
                        <span class="icon icon-vip"></span>
                    </span>
                    <span data-bind="if: chatter.isLookingForMan"></span>
                    <span data-bind="if: chatter.isLookingForWoman">
                        <span class="icon icon-woman text-woman" title="Looking for a woman"></span>
                    </span>
                    <span data-bind="if: chatter.isLookingForBoth"></span>
                    <span data-bind="if: chatter.vip &amp;&amp; chatter.isLookingForUnknown"></span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
                        </div>
                        <div class="col-xs-1 col-sm-3 col-md-2 col-lg-2 border actions text-vip">
                            <div class="pointer text-center awaiting-reply">
                                <span class="icon icon-new-message fs-2x" data-bind="click: $parent.showConversation"></span>
                                <span class="text" data-bind="click: $parent.showConversation">Reply</span>
                            </div>
                        </div>
                        <div class="col-xs-1 col-sm-3 col-md-2 col-lg-2 actions text-vip">
                            <div class="pointer text-center">
                                <span class="icon icon-delete fs-2x" data-bind="click: $parent.deleteInterlocutor"></span>
                                <span class="text" data-bind="click: $parent.deleteInterlocutor">Delete</span>
                            </div>
                        </div>
                    </li>